### ISSUE TITLE
Registry.BLOCK non existent in net.minecraft.core.Registry

### ISSUE THREAD

**Issue by F9Alejandro** [AzortisCode/Orbis#8]
https://github.com/AzortisCode/Orbis/blob/65525cafa0553eaf977dcc957f8977ef720ac810/orbis-paper/src/main/java/com/azortis/orbis/paper/block/PaperBlockRegistry.java#L55-L57

Recommend replacing Registry.BLOCK to BuiltInRegistries.BLOCK.
Registry.BLOCK is deprecated according to Forge JavaDocs for net.minecraft.core.Registry.

**Comment by JakeNijssen** [comment]
Correct, I knew about this error just never tried to compile so didn't find the error everywhere, this was due to NMS version bump. Thanks for pointing it out. Fix: Change registry -> BuiltInRegistry

**Comment by F9Alejandro** [comment]
All good, I will try and see if there are more. I did end up bypassing tests on core though. Seems override doesn't want to work properly :/

**Comment by JakeNijssen** [comment]
Those tests are broken anyways, its hard to test the core standalone since it requires me to mock a platform. So one day when I hate myself I'll start writing the tests again.

**Comment by JakeNijssen** [comment]
Fixed this in latest commits.
